# Generated by Django 5.1.5 on 2025-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0003_alter_condition_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcycle",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="workcycle",
            name="timestamp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
