# Generated by Django 5.1.5 on 2025-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0004_alter_workcycle_options_workcycle_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workcycle",
            name="timestamp",
            field=models.DateField(),
        ),
    ]
