# Generated by Django 5.1.5 on 2025-09-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0005_alter_workcycle_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["value"],
            },
        ),
    ]
