# Generated by Django 5.1.5 on 2025-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0006_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcycle",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
