# Generated by Django 5.1.5 on 2025-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0007_workcycle_is_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
