# Generated by Django 5.1.5 on 2025-09-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0008_agreementstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objective",
            options={"ordering": ["group"]},
        ),
    ]
