# Generated by Django 5.1.5 on 2025-09-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0009_alter_objective_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.objectivegroup",
            ),
        ),
    ]
