# Generated by Django 5.1.5 on 2025-10-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0010_alter_objective_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementstatus",
            options={"verbose_name_plural": "Project agreement statuses"},
        ),
        migrations.AlterModelOptions(
            name="condition",
            options={"ordering": ["objective__name", "level__value"]},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["value"], "verbose_name": "Maturity level"},
        ),
        migrations.AlterModelOptions(
            name="projectstatus",
            options={
                "verbose_name": "Project review status",
                "verbose_name_plural": "Project review statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="reason",
            options={
                "ordering": ["value"],
                "verbose_name": "Objective unstarted reason",
            },
        ),
        migrations.AlterModelOptions(
            name="workcycle",
            options={"ordering": ["timestamp"], "verbose_name": "Cycle"},
        ),
        migrations.AlterField(
            model_name="workcycle",
            name="is_current",
            field=models.BooleanField(
                default=False, verbose_name="Is the current cycle"
            ),
        ),
        migrations.AlterField(
            model_name="workcycle",
            name="timestamp",
            field=models.DateField(verbose_name="Ends"),
        ),
    ]
