# Generated by Django 5.2.7 on 2025-10-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_alter_agreementstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AlterModelOptions(
            name='objectivegroup',
            options={'ordering': ['id']},
        ),
    ]
