# Generated by Django 5.2.7 on 2025-10-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_alter_agreementstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.TextField(max_length=400),
        ),
    ]
