# Generated by Django 5.2.7 on 2025-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0012_alter_objective_options_alter_objectivegroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.TextField(max_length=400),
        ),
    ]
