# Generated by Django 5.1.5 on 2025-09-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0006_reason"),
        ("projects", "0002_alter_levelcommitment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectobjective",
            name="if_not_started",
        ),
        migrations.AddField(
            model_name="projectobjective",
            name="unstarted_reason",
            field=models.ForeignKey(
                blank=True,
                help_text="Will be overridden by <em>Status</em> if appropriate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.reason",
            ),
        ),
    ]
