# Generated by Django 5.1.5 on 2025-09-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0008_agreementstatus"),
        ("projects", "0003_remove_projectobjective_if_not_started_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="agreement_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.agreementstatus",
            ),
        ),
    ]
