# Generated by Django 5.1.5 on 2025-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_agreement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectobjectivecondition",
            name="candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectobjectivecondition",
            name="not_applicable",
            field=models.BooleanField(default=False),
        ),
    ]
