# Generated by Django 5.1.5 on 2025-09-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectobjectivecondition_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectobjectivecondition",
            name="evidence",
            field=models.TextField(default=""),
        ),
    ]
