# Generated by Django 5.1.5 on 2025-09-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectobjectivecondition_evidence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectobjectivecondition",
            name="evidence",
        ),
    ]
