# Generated by Django 5.1.5 on 2025-09-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0010_alter_objective_group"),
        ("projects", "0007_remove_projectobjectivecondition_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="agreement_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.agreementstatus",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.projectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_review_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.projectstatus",
            ),
        ),
    ]
