# Generated by Django 5.1.5 on 2025-09-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0010_alter_objective_group"),
        (
            "projects",
            "0008_alter_project_agreement_status_alter_project_group_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelCommitment",
            new_name="Commitment",
        ),
    ]
