# Generated by Django 5.1.5 on 2025-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_rename_levelcommitment_commitment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectobjective",
            options={"ordering": ["objective"]},
        ),
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(default="", null=True),
        ),
    ]
