# Generated by Django 5.1.5 on 2025-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_projectobjective_options_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
