# Generated by Django 5.1.5 on 2025-09-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'ordering': ['name']},
        ),
    ]
