# Generated by Django 5.1.5 on 2025-10-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_projectgroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qi",
            options={
                "ordering": ["project__name", "workcycle"],
                "verbose_name": "Quality indicator",
            },
        ),
    ]
