# Generated by Django 5.1.5 on 2025-10-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_qi_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectobjectivecondition",
            name="status",
            field=models.CharField(
                choices=[
                    ("NA", "not applicable"),
                    ("CA", "candidate"),
                    ("DO", "done"),
                    ("", "none"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
