# Generated by Django 5.1.13 on 2025-10-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_migrate_to_unified_status_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectobjectivecondition",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="projectobjectivecondition",
            name="done",
        ),
        migrations.RemoveField(
            model_name="projectobjectivecondition",
            name="not_applicable",
        ),
    ]
