# Generated by Django 5.2 on 2025-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_projectobjectivecondition_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobjectivecondition',
            name='status',
            field=models.CharField(choices=[('NA', 'not-applicable'), ('CA', 'candidate'), ('DO', 'done'), ('', 'none')], default='', max_length=2),
        ),
    ]
