# Generated by Django 5.2.7 on 2025-10-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_projectobjectivecondition_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectobjective',
            options={'ordering': ['project', 'objective']},
        ),
    ]
