# Generated by Django 5.2.7 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_projectobjective_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
