# Generated by Django 5.2.7 on 2025-11-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0013_alter_condition_name"),
        ("projects", "0019_alter_project_name_alter_projectgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="current_qi",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectobjective",
            name="level_achieved",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="framework.level",
            ),
        ),
    ]
