name: Publish to edge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-charm:
    name: Publish charm and rock
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        arch: [amd64, arm64]
    runs-on: [self-hosted, linux, "${{ matrix.arch }}"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: setup lxd
        uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee  # v1
      - name: build rock
        run: |
          set -x
          sudo snap install --channel latest/stable --classic rockcraft
          rockcraft pack --verbosity trace
          docker run -d -p 5000:5000 --name registry registry:latest
          rockcraft.skopeo --insecure-policy copy --dest-tls-verify=false oci-archive:$(ls *.rock) docker://localhost:5000/dashboard:latest
      - name: upload rock
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: rock-${{ matrix.arch }}
          path: "*.rock"
      - run: |
          docker pull localhost:5000/dashboard:latest
      - name: build charm
        id: charmcraft
        working-directory: charm
        run: |
          set -x
          sudo snap install --channel latest/stable --classic charmcraft
          charmcraft pack --verbosity trace
          echo charms=`ls *.charm` >> $GITHUB_OUTPUT
      - name: upload charm
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: charm-${{ matrix.arch }}
          path: ./charm/${{ steps.charmcraft.outputs.charms }}
      - run: |
          sudo apt update && sudo apt install python3-yaml -y
      - name: expand charmcraft.yaml
        working-directory: charm
        run: |
          charmcraft expand-extensions > ../charmcraft.yaml
      - name: update upstream-source
        shell: python
        run: |
          import yaml
          
          charmcraft_yaml = yaml.safe_load(open("charmcraft.yaml"))
          resources = charmcraft_yaml["resources"]
          resources[list(resources)[0]]["upstream-source"] = "localhost:5000/dashboard:latest"
          yaml.dump(charmcraft_yaml, open("charmcraft.yaml", "w"), sort_keys=False)
      - name: show charmcraft.yaml
        run: |
          cat charmcraft.yaml
      - name: publish charm
        uses: canonical/charming-actions/upload-charm@1753e0803f70445132e92acd45c905aba6473225  # 2.7.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          built-charm-path: ./charm/${{ steps.charmcraft.outputs.charms }}
          tag-prefix: ${{ matrix.arch }}
